contact_links:
  - name: 3. Discussions / forums
    url: https://github.com/silexlabs/Silex/discussions
    about: Ask your questions, share ideas, showcase your work
  - name: 4. Silex PRO
    url: http://eepurl.com/gjYnib
    about: To be listed as a professional selling Silex websites please join this group
  - name: 5. Community chat
    url: https://gitter.im/silex-website-builder/community
    about: "Let's get in touch and talk about Silex" 
  - name: 6. Documentation
    url: https://github.com/silexlabs/Silex/wiki
    about: "Read the f**ng manual ;) This is a collaborative effort, please document what you learned" 
